calendarapp/urls.py
from django.urls import path

from . import views

app_name = "calendarapp"


urlpatterns = [
    path('collab/view-initiated/<str:id1>/schedules/', views.CalendarViewNew.as_view(), name="schedules-initiated"),
    path('collab/view-accepted/<str:id1>/schedules/', views.CalendarViewNew.as_view(), name="schedules-accepted"),
    path('collab/view-initiated/<str:id1>/all-schedules/', views.showAllEventsInitiated, name="all-schedules-initiated"),
    path('collab/view-accepted/<str:id1>/all-schedules/', views.showAllEventsInitiated, name="all-schedules-accepted"),
    path('collab/view-initiated/<str:id1>/all-schedules/select/<str:id2>', views.selectEventInitiated, name='select_event_initiated'),
    path('collab/view-initiated/<str:id1>/all-schedules/deselect/<str:id2>', views.deselectEventInitiated, name='deselect_event_initiated'),
    path('collab/view-accepted/<str:id1>/all-schedules/select/<str:id2>', views.selectEventInitiated, name='select_event_accepted'),
    path('collab/view-accepted/<str:id1>/all-schedules/deselect/<str:id2>', views.deselectEventInitiated, name='deselect_event_accepted'),
    path('collab/view-initiated/<str:id1>/all-schedules/delete-all', views.deleteAllEventsInitiated, name='delete_all_events_initiated'),
    path('collab/view-accepted/<str:id1>/all-schedules/delete-all', views.deleteAllEventsInitiated, name='delete_all_events_accepted'),

    path('collab/view-initiated/schedules/<str:id1>/<str:id2>', views.showEventInitiated, name='show_event_initiated'),
    path('collab/view-accepted/schedules/<str:id1>/<str:id2>', views.showEventInitiated, name='show_event_accepted'),

    path('collab/view-initiated/schedules/<str:id1>/<str:id2>', views.showEventInitiated2, name='show_event_initiated2'),


    path('collab/view-initiated/schedules/<str:id1>/<str:id2>/update', views.updateEventInitiated, name='update_event_initiated'),
    path('collab/view-accepted/schedules/<str:id1>/<str:id2>/update', views.updateEventInitiated, name='update_event_accepted'),

    path('collab/view-initiated/schedules/<str:id1>/<str:id2>/delete', views.deleteEventInitiated, name='delete_event_initiated'),
    path('collab/view-accepted/schedules/<str:id1>/<str:id2>/delete', views.deleteEventInitiated, name='delete_event_accepted'),

    path("collab/view-initiated/schedule/<str:id1>", views.create_event, name="event_new"),

    path("calenders/", views.CalendarView.as_view(), name="calendars"),

    path("event/<int:event_id>/details/", views.event_details, name="event-detail"),
    path(
        "add_eventmember/<int:event_id>", views.add_eventmember, name="add_eventmember"
    ),
    path(
        "event/<int:pk>/remove",
        views.EventMemberDeleteView.as_view(),
        name="remove_event",
    ),
    path("all-event-list/", views.AllEventsListView.as_view(), name="all_events"),
    path(
        "running-event-list/",
        views.RunningEventsListView.as_view(),
        name="running_events",
    ),
]

chat/urls.py
from django.urls import path
from chat import views

urlpatterns = [
    path('<str:id>/chat/', views.index, name='chat'),
    path('chat/<str:room_name>/', views.Room.as_view(), name='room'),
    path('envelope-notification', views.clearEnvelopeUnreads, name='envelope_notification'),
    path('envelope-notifications', views.showChatNotifications, name='envelope_notifications'),

]

etal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('account.urls')),
    path('', include('chat.urls')),
    path('adm/', admin.site.urls),
    path('', include('home.urls')),
    path("", include("calendarapp.urls")),
    path("", include("researchnote.urls")),
    path("", include("community.urls")),
    path("", include("subscription.urls")),

# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

calendarapp/models/event.py
from datetime import datetime
from django.db import models
from django.urls import reverse
from calendarapp.models import EventAbstract
from account.models import Researcher, Collab
from django.utils import timezone

class EventManager(models.Manager):
    """ Event manager """

    def get_all_events(self, user):
        events = Event.objects.filter(user=user, is_active=True, is_deleted=False)
        return events

    def get_running_events(self, user):
        running_events = Event.objects.filter(
            user=user,
            is_active=True,
            is_deleted=False,
            end_time__gte=datetime.now().date(),
        ).order_by("start_time")
        return running_events

class EventAvailable(models.Model):
    AVAILABLE_CHOICES = [
        ('Yes','Yes'),
        ('No', 'No'),
        ('Maybe', 'Maybe')
    ]
    available = models.CharField(max_length=5, choices=AVAILABLE_CHOICES, default='Yes', null=True)
    creator = models.ForeignKey(Researcher, null=True, blank=True, on_delete=models.SET_NULL, related_name="event_creator")
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True, null=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        try:
            return str(self.available)
        except:
            return str(self.id)

class Event(EventAbstract):
    """ Event model """
    user = models.ForeignKey(Researcher, on_delete=models.CASCADE, related_name="events")
    collab = models.ForeignKey(Collab, null=True, blank=True, on_delete=models.SET_NULL, related_name="collab_scheduler")
    title = models.CharField(max_length=200, verbose_name="")
    available_choice = models.ManyToManyField(EventAvailable, blank=True, verbose_name="Available", related_name="update_text")
    end_time = models.DateTimeField(null=True, blank=True, verbose_name="Ending Time")
    location = models.CharField(max_length=200, null=True, blank=True, verbose_name="")
    link = models.CharField(max_length=200,  null=True, blank=True, verbose_name="")
    description = models.TextField(null=True, blank=True, verbose_name="")
    is_selected = models.ManyToManyField(Researcher, blank=True, related_name="is_selected_event")
    start_time = models.DateTimeField(null=True, blank=True, verbose_name="Starting Time")
    reminder = models.DateTimeField(blank=True, null= True)

    objects = EventManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("calendarapp:event-detail", args=(self.id,))

    @property
    def get_html_url(self):
        url = reverse("calendarapp:event-detail", args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

calendarapp/models/event_abstract.py
from django.db import models


class EventAbstract(models.Model):
    """ Event abstract model """

    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

calendarapp/views/event_list.py
from django.views.generic import ListView

from calendarapp.models import Event


class AllEventsListView(ListView):
    """ All event list views """

    template_name = "calendarapp/events_list.html"
    model = Event

    def get_queryset(self):
        return Event.objects.get_all_events(user=self.request.user)


class RunningEventsListView(ListView):
    """ Running events list view """

    template_name = "calendarapp/events_list.html"
    model = Event

    def get_queryset(self):
        return Event.objects.get_running_events(user=self.request.user)

calendarapp/views/other_views.py
# cal/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.views import generic
from django.utils.safestring import mark_safe
from datetime import timedelta, datetime, date
import calendar
from account.filters import InitiatedAllEventsFilter
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from account.models import Collab
from calendarapp.models import EventMember, Event, EventAvailable
from calendarapp.utils import Calendar
from calendarapp.forms import EventForm, EventUpdateForm, AddMemberForm, AvailableForm
from django.contrib import messages
from django.core.paginator import Paginator

def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split("-"))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = "month=" + str(prev_month.year) + "-" + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = "month=" + str(next_month.year) + "-" + str(next_month.month)
    return month

class CalendarView(LoginRequiredMixin, generic.ListView):
    login_url = "login"
    model = Event
    template_name = "calendar.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get("month", None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context["calendar"] = mark_safe(html_cal)
        context["prev_month"] = prev_month(d)
        context["next_month"] = next_month(d)
        return context

@login_required(login_url="login")
def create_event(request, id1, **kwargs):
    collab = Collab.objects.get(id=id1)
    collab_id = collab.id
    if collab.researcher == request.user:
        form = EventForm(request.POST or None)
        if request.POST and form.is_valid():
            title = form.cleaned_data["title"]
            description = form.cleaned_data["description"]
            location = form.cleaned_data["location"]
            link = form.cleaned_data["link"]
            start_time = request.GET.get('startdate')
            end_time = form.cleaned_data["end_time"]
            reminder = form.cleaned_data["reminder"]
            Event.objects.get_or_create(
                user=request.user,
                collab = collab,
                title=title,
                description=description,
                location=location,
                link=link,
                start_time=start_time,
                end_time=end_time,
                reminder=reminder,
            )
            messages.info(request, "The schedule has been added successfully")
            return redirect("calendarapp:schedules-initiated", id1)
        # else:
        #     messages.error(request, "Please review form input fields below")
        return render(request, "calendarapp/event.html", {"form": form, 'collab': collab, 'collab_id': collab_id})
    elif request.user in collab.collaborators.all():
        form = EventForm(request.POST or None)
        if request.POST and form.is_valid():
            title = form.cleaned_data["title"]
            description = form.cleaned_data["description"]
            location = form.cleaned_data["location"]
            link = form.cleaned_data["link"]
            start_time = request.GET.get('startdate')
            end_time = form.cleaned_data["end_time"]
            reminder = form.cleaned_data["reminder"]
            Event.objects.get_or_create(
                user=request.user,
                collab = collab,
                title=title,
                description=description,
                location=location,
                link=link,
                start_time=start_time,
                end_time=end_time,
                reminder=reminder,
            )
            messages.info(request, "The schedule has been added successfully")
            return redirect("calendarapp:schedules-initiated", id1)
        else:
            messages.error(request, "Please review form input fields below")
        return render(request, "calendarapp/event.html", {"form": form, 'collab': collab, 'collab_id': collab_id})
    else:
        return redirect('collab')

@login_required(login_url="join")
def event_details(request, event_id):
    event = Event.objects.get(id=event_id)
    eventmember = EventMember.objects.filter(event=event)
    context = {"event": event, "eventmember": eventmember}
    return render(request, "event-details.html", context)

def add_eventmember(request, event_id):
    forms = AddMemberForm()
    if request.method == "POST":
        forms = AddMemberForm(request.POST)
        if forms.is_valid():
            member = EventMember.objects.filter(event=event_id)
            event = Event.objects.get(id=event_id)
            if member.count() <= 9:
                user = forms.cleaned_data["user"]
                EventMember.objects.create(event=event, user=user)
                return redirect("calendarapp:calendar")
            else:
                print("--------------User limit exceed!-----------------")
    context = {"form": forms}
    return render(request, "add_member.html", context)


class EventMemberDeleteView(generic.DeleteView):
    model = EventMember
    template_name = "event_delete.html"
    success_url = reverse_lazy("calendarapp:calendar")


class CalendarViewNew(LoginRequiredMixin, generic.View):
    login_url = "login"
    template_name = "calendarapp/calendar.html"
    form_class = EventForm

    def get(self, request, id1, *args, **kwargs):
        collab = Collab.objects.get(id=id1)
        if request.user == collab.researcher:
            forms = self.form_class()
            events = Event.objects.filter(collab=collab)
            events_month = Event.objects.filter(collab=collab, end_time__gte=datetime.now().date())
            event_list = []
            # start: '2020-09-16T16:00:00'
            for event in events:
                event_list.append(
                    {
                        "title": event.title,
                        "start": event.start_time.strftime("%Y-%m-%dT%H:%M:%S"),
                        "end": event.end_time.strftime("%Y-%m-%dT%H:%M:%S"),

                    }
                )
            context = {"form": forms, 'collab':collab, "events": event_list,
                       "events_month": events_month}
            return render(request, self.template_name, context)
        elif request.user in collab.collaborators.all():
            forms = self.form_class()
            events = Event.objects.filter(collab=collab)
            events_month = Event.objects.filter(collab=collab, end_time__gte=datetime.now().date())
            event_list = []
            # start: '2020-09-16T16:00:00'
            for event in events:
                event_list.append(
                    {
                        "title": event.title,
                        "start": event.start_time.strftime("%Y-%m-%dT%H:%M:%S"),
                        "end": event.end_time.strftime("%Y-%m-%dT%H:%M:%S"),

                    }
                )
            context = {"form": forms, 'collab':collab, "events": event_list,
                       "events_month": events_month}
            return render(request, self.template_name, context)
        else:
            return redirect('collab')


    def post(self, request, id1, *args, **kwargs):
        collab = Collab.objects.get(id=id1)
        forms = self.form_class(request.POST)
        if forms.is_valid():
            form = forms.save(commit=False)
            form.user = request.user
            form.collab = collab
            form.save()
            return redirect("calendarapp:schedules-initiated", id1)
        context = {"form": forms}

        return render(request, self.template_name, context)

@login_required
def showAllEventsInitiated(request, id1):
    collab = Collab.objects.get(id=id1)
    if collab.researcher == request.user:
        context = {}
        filtered_all_events = InitiatedAllEventsFilter(
            request.GET,
            queryset = Event.objects.filter(collab__id=id1)
        )
        context['filtered_all_events'] = filtered_all_events
        paginated_filtered_all_events = Paginator(filtered_all_events.qs, 99)
        page_number = request.GET.get('page')
        all_events_page_obj = paginated_filtered_all_events.get_page(page_number)
        context['all_events_page_obj'] = all_events_page_obj
        total_all_events = filtered_all_events.qs.count()
        context['total_all_events'] = total_all_events
        context['collab'] = collab

        return render(request, 'calendarapp/all_events.html', context)
    elif request.user in collab.collaborators.all():
        context = {}
        filtered_all_events = InitiatedAllEventsFilter(
            request.GET,
            queryset = Event.objects.filter(collab__id=id1)
        )
        context['filtered_all_events'] = filtered_all_events
        paginated_filtered_all_events = Paginator(filtered_all_events.qs, 99)
        page_number = request.GET.get('page')
        all_events_page_obj = paginated_filtered_all_events.get_page(page_number)
        context['all_events_page_obj'] = all_events_page_obj
        total_all_events = filtered_all_events.qs.count()
        context['total_all_events'] = total_all_events
        context['collab'] = collab

        return render(request, 'calendarapp/all_events.html', context)
    else:
        return redirect('collab')

@login_required
def selectEventInitiated(request, id1, id2, **kwargs):
    collab = Collab.objects.get(id=id1)

templates/calendarapp/all_events.html
{% extends 'board.html' %}


{% block title %}
<title>Schedules</title>
{% endblock title %}

{% block content %}
<div class="app-content bg-white">
					<div class="side-app">
            {% include '_alerts.html' %}
    				<br>

              <div class="container content-area">
                <div class="horizontal-content">
                    <div class="row">
                      <div class="col-md-12">
                        <div class="card">
                          <div class="card-header">
                            <div class="col-md-12">
                              <div class="float-right text-right">
                                <div class="card-options">
                                  <span class="dropdown-toggle fs-16" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"><i class="fa fa-ellipsis-v" ></i></span>
                                  {% for event in all_events_page_obj %}
                                  {% if request.user in event.is_selected.all %}
                                  <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                    <li><a href="delete-all"><i class="fa fa-trash mr-2"></i>Delete Selected</a></li>
                                  </ul>
                                  {% endif %}
                                  {% endfor %}
                                </div>
                              </div>
                            </div>

                          </div>
                          <div class="card-body">
                            <div class="table-responsive mb-0">
                              <table class="table table-bordered table-hover mb-0 text-nowrap">
                                <thead>
                                  <tr>
                                    <th>Title</th>
                                    <th>Start Time</th>
                                    <th>End Time</th>
                                    <!-- <th>Created by</th>
                                    <th>Description</th>
                                    <th>Link</th>
                                    <th>Location</th> -->
                                    <th>Selected</th>
                                    <th></th>
                                  </tr>
                                </thead>
                                <tbody>
                                  {% for event in all_events_page_obj %}
                                  {% if request.user in event.is_selected.all %}
                                  <tr class="bg-info">
                                    <td><a class="text-white" href="deselect/{{event.id}}">{{event.title}}</a></td>
                                    <td class="num-font"><a class="text-white" href="deselect/{{event.id}}">{{event.start_time}}</a></td>
                                    <td class="num-font"><a class="text-white" href="deselect/{{event.id}}">{{event.end_time}}</a></td>
                                    <!-- <td class="num-font"><a class="text-white" href="deselect/{{event.id}}">{{event.user}}</a></td>
                                    <td class="num-font"><a class="text-white" href="deselect/{{event.id}}">{{event.description}}</a></td>
                                    <td class="num-font"><a class="text-white" href="deselect/{{event.id}}">{{event.link}}</a></td>
                                    <td class="num-font"><a class="text-white" href="deselect/{{event.id}}">{{event.location}}</a></td> -->
                                    <td class="text-center"><a class="text-white" href="deselect/{{event.id}}"><i class="fa fa-check-circle"></i></a></td>
                                    <td>
                                      <div class="card-options">
                                        <span class="dropdown-toggle fs-16" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"><i class="fa fa-ellipsis-v" ></i></span>
                                        <ul class="dropdown-menu dropdown-menu-right" role="menu">
																					{% if request.user == collab.researcher %}
                                          <li><a href="{% url 'calendarapp:show_event_initiated' collab.id event.id %}"><i class="fa fa-eye mr-2"></i>View</a></li>
																					<li>{% if event.user == request.user %} <a href="{% url 'calendarapp:update_event_initiated' collab.id event.id %}"><i class="fa fa-edit mr-2"></i>Edit</a> {% else %} {% endif %}</li>
																					{% elif request.user in collab.collaborators.all %}
                                          <li><a href="{% url 'calendarapp:show_event_accepted' collab.id event.id %}"><i class="fa fa-eye mr-2"></i>View</a></li>
																					<li>{% if event.user == request.user %} <a href="{% url 'calendarapp:update_event_accepted' collab.id event.id %}"><i class="fa fa-edit mr-2"></i>Edit</a> {% else %} {% endif %}</li>

																					{% endif %}

                                        </ul>
                                      </div>
                                    </td>
                                  </tr>
                                  {% else %}
                                  <tr>
                                    <td><a href="all-schedules/deselect/{{event.id}}">{{event.title}}</a></td>
                                    <td class="num-font"><a href="select/{{event.id}}">{{event.start_time}}</a></td>
                                    <td class="num-font"><a href="select/{{event.id}}">{{event.end_time}}</a></td>
                                    <!-- <td class="num-font"><a href="select/{{event.id}}">{{event.user}}</a></td>
                                    <td class="num-font"><a href="select/{{event.id}}">{{event.description}}</a></td>
                                    <td class="num-font"><a href="select/{{event.id}}">{{event.link}}</a></td>
                                    <td class="num-font"><a href="select/{{event.id}}">{{event.location}}</a></td> -->
                                    <td class="text-center"></td>
                                    <td>
                                      <div class="card-options">
                                        <span class="dropdown-toggle fs-16" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"><i class="fa fa-ellipsis-v" ></i></span>
																				<ul class="dropdown-menu dropdown-menu-right" role="menu">
																					{% if request.user == collab.researcher %}
                                          <li><a href="{% url 'calendarapp:show_event_initiated' collab.id event.id %}"><i class="fa fa-eye mr-2"></i>View</a></li>
																					<li>{% if event.user == request.user %} <a href="{% url 'calendarapp:update_event_initiated' collab.id event.id %}"><i class="fa fa-edit mr-2"></i>Edit</a> {% else %} {% endif %}</li>
																					{% elif request.user in collab.collaborators.all %}
                                          <li><a href="{% url 'calendarapp:show_event_accepted' collab.id event.id %}"><i class="fa fa-eye mr-2"></i>View</a></li>
																					<li>{% if event.user == request.user %} <a href="{% url 'calendarapp:update_event_accepted' collab.id event.id %}"><i class="fa fa-edit mr-2"></i>Edit</a> {% else %} {% endif %}</li>
																					{% endif %}
                                        </ul>

                                      </div>
                                    </td>
                                  </tr>
                                  {% endif %}
                                  {% endfor %}
                                </tbody>
                              </table>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
              </div>
          </div>
      </div>
{% endblock content %}

templates/calendarapp/event.html
{% extends 'board.html' %}
{% load crispy_forms_tags %}
{% block title %}
<title>Schedule</title>
{% endblock %}
{% block content %}
<div class="app-content bg-white">
          <div class="side-app">
            <br>
            
              <div class="container content-area">
                <div class="horizontal-content">
                  {% include '_alerts.html' %}

                  <div class="row">
                    <div class="col-md-12 col-xl-12 col-lg-12">
                    <div class="card">
                      <form method="post" class="form-group col-lg-12 text-info" enctype="multipart/form-data">
                        <div class="card-header bg-white">
                          <h4 class="text-info">
                            <i class="fas fa-calendar-check"></i> Schedule</h4>
                        </div>
                        <br>
                        {% csrf_token %}
                        <div class="form-row">
                          <div class="form-group col-sm-12 mb-2">
                                {{ form.title|as_crispy_field }}
                          </div>
                        </div>
                        <div class="form-row">
                          <div class="form-group col-sm-12 mb-2">
                                {{ form.end_time|as_crispy_field }}
                          </div>
                        </div>
                        <div class="form-row">
                          <div class="form-group col-sm-12 mb-2">
                                {{ form.location|as_crispy_field }}
                          </div>
                        </div>
                        <div class="form-row">
                          <div class="form-group col-sm-12 mb-2">
                                {{ form.description|as_crispy_field }}
                          </div>
                        </div>
                        <div class="form-row">
                          <div class="form-group col-sm-12 mb-2">
                                {{ form.link|as_crispy_field }}
                          </div>
                        </div>
                        <div class="form-row">
                          <div class="form-group col-sm-12 mb-2">
                                {{ form.reminder|as_crispy_field }}
                          </div>
                        </div>
                        <div style="text-align:left" class="mt-1">
                        <input type="submit" value="OK" class="btn btn-dark-blue">
                    </form>
                    </div>
                    </div>
                  </div>


                </div>
              </div>
            </div>
          </div>
{% endblock %}

templates/calendarapp/event_confirm_delete.html
{% extends 'board.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load humanize %}
{% load home_tags %}
{% block title %}
  <title>Event</title>
  <meta name="description" content="">

{% endblock title %}

{% block content %}
{% include '_alerts.html' %}
<div class=" app-content">
	<div class="side-app">
  <br>
    <div class="container content-area">
      <div class="horizontal-content">
        <div class="row">
          <div class="d-flex justify-content-center">
            <div class="text-center card bg-info text-white form-group col-md-9">
              <br>
                {% if event.user == request.user %}
                <h4 > <span class="text-red">CAUTION!</span> Deleting {{event.title}} will affect all the information associated with the event. Do you still wish to continue?</h4>
                <br>
                <form method="post">
                  {% csrf_token %}
                  {{ form|crispy }}
                  {% if request.user == collab.researcher %}
                  <input type="submit" class="btn btn-danger" value="Yes, delete"> <a class="btn btn-outline-light" href="{% url 'calendarapp:show_event_initiated' collab.id event.id %}">No, cancel</a>
                  {% elif request.user in collab.collaborators.all %}
                  <input type="submit" class="btn btn-danger" value="Yes, delete"> <a class="btn btn-outline-light" href="{% url 'calendarapp:show_event_accepted' collab.id event.id %}">No, cancel</a>
                  {% endif %}
                </form>
                {% else %}
                <h2 class="text-center">Access Denied!</h2>
                <br>
                {% endif %}
                <br>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content%}

templates/calendarapp/events_confirm_delete_initiated.html
{% extends 'board.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load humanize %}
{% load home_tags %}
{% block title %}
  <title>Delete</title>
  <meta name="description" content="">

{% endblock title %}

{% block content %}
{% include '_alerts.html' %}
<div class=" app-content">
	<div class="side-app">
  <br>
    <div class="container content-area">
      <div class="horizontal-content">
        <div class="row">
          <div class="d-flex justify-content-center">
            <div class="text-center card bg-info text-white form-group col-md-9">
              <br>
                <h4 > <span class="text-red">CAUTION!</span> Do you still wish to continue?</h4>
                <br>
                <form method="post">
                  {% csrf_token %}
                  {{ form|crispy }}
                  <input type="submit" class="btn btn-danger" value="Yes, delete"> <a class="btn btn-outline-light" href="{% url 'calendarapp:all-schedules-initiated' collab.id  %}">No, cancel</a>
                </form>
                <br>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content%}