calendarapp/urls.py
from django.urls import path

from . import views

app_name = "calendarapp"


urlpatterns = [
    path('collab/view-initiated/<str:id1>/schedules/', views.CalendarViewNew.as_view(), name="schedules-initiated"),
    path('collab/view-accepted/<str:id1>/schedules/', views.CalendarViewNew.as_view(), name="schedules-accepted"),
    path('collab/view-initiated/<str:id1>/all-schedules/', views.showAllEventsInitiated, name="all-schedules-initiated"),
    path('collab/view-accepted/<str:id1>/all-schedules/', views.showAllEventsInitiated, name="all-schedules-accepted"),
    path('collab/view-initiated/<str:id1>/all-schedules/select/<str:id2>', views.selectEventInitiated, name='select_event_initiated'),
    path('collab/view-initiated/<str:id1>/all-schedules/deselect/<str:id2>', views.deselectEventInitiated, name='deselect_event_initiated'),
    path('collab/view-accepted/<str:id1>/all-schedules/select/<str:id2>', views.selectEventInitiated, name='select_event_accepted'),
    path('collab/view-accepted/<str:id1>/all-schedules/deselect/<str:id2>', views.deselectEventInitiated, name='deselect_event_accepted'),
    path('collab/view-initiated/<str:id1>/all-schedules/delete-all', views.deleteAllEventsInitiated, name='delete_all_events_initiated'),
    path('collab/view-accepted/<str:id1>/all-schedules/delete-all', views.deleteAllEventsInitiated, name='delete_all_events_accepted'),

    path('collab/view-initiated/schedules/<str:id1>/<str:id2>', views.showEventInitiated, name='show_event_initiated'),
    path('collab/view-accepted/schedules/<str:id1>/<str:id2>', views.showEventInitiated, name='show_event_accepted'),

    path('collab/view-initiated/schedules/<str:id1>/<str:id2>', views.showEventInitiated2, name='show_event_initiated2'),


    path('collab/view-initiated/schedules/<str:id1>/<str:id2>/update', views.updateEventInitiated, name='update_event_initiated'),
    path('collab/view-accepted/schedules/<str:id1>/<str:id2>/update', views.updateEventInitiated, name='update_event_accepted'),

    path('collab/view-initiated/schedules/<str:id1>/<str:id2>/delete', views.deleteEventInitiated, name='delete_event_initiated'),
    path('collab/view-accepted/schedules/<str:id1>/<str:id2>/delete', views.deleteEventInitiated, name='delete_event_accepted'),

    path("collab/view-initiated/schedule/<str:id1>", views.create_event, name="event_new"),

    path("calenders/", views.CalendarView.as_view(), name="calendars"),

    path("event/<int:event_id>/details/", views.event_details, name="event-detail"),
    path(
        "add_eventmember/<int:event_id>", views.add_eventmember, name="add_eventmember"
    ),
    path(
        "event/<int:pk>/remove",
        views.EventMemberDeleteView.as_view(),
        name="remove_event",
    ),
    path("all-event-list/", views.AllEventsListView.as_view(), name="all_events"),
    path(
        "running-event-list/",
        views.RunningEventsListView.as_view(),
        name="running_events",
    ),
]

chat/urls.py
from django.urls import path
from chat import views

urlpatterns = [
    path('<str:id>/chat/', views.index, name='chat'),
    path('chat/<str:room_name>/', views.Room.as_view(), name='room'),
    path('envelope-notification', views.clearEnvelopeUnreads, name='envelope_notification'),
    path('envelope-notifications', views.showChatNotifications, name='envelope_notifications'),

]

etal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('account.urls')),
    path('', include('chat.urls')),
    path('adm/', admin.site.urls),
    path('', include('home.urls')),
    path("", include("calendarapp.urls")),
    path("", include("researchnote.urls")),
    path("", include("community.urls")),
    path("", include("subscription.urls")),

# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

researchnote/urls.py
from django.urls import path
from researchnote import views

urlpatterns = [
    path('collab/view-initiated/<str:id1>/notes', views.showNotesInitiated, name='notes_initiated'),
    path('collab/view-initiated/<str:id1>/notes/<str:id2>', views.showNoteInitiated, name='show_note_initiated'),
    path('collab/view-accepted/<str:id1>/notes/<str:id2>', views.showNoteInitiated, name='show_note_accepted'),
    path('collab/view-accepted/<str:id1>/notes', views.showNotesInitiated, name='notes_accepted'),

    path('collab/view-initiated/<str:id1>/notes/delete/<str:id2>', views.deleteNoteInitiated, name='delete_note_initiated'),
    path('collab/view-accepted/<str:id1>/notes/delete/<str:id2>', views.deleteNoteInitiated, name='delete_note_accepted'),

    path('collab/view-initiated/<str:id1>/notes/pin/<str:id2>', views.pinNote, name='pin_note'),
    path('collab/view-accepted/<str:id1>/notes/pin/<str:id2>', views.pinNote, name='pin_note'),
    #
    # path('collab/view-initiated/<str:id1>/collab-docs/select/<str:id2>', views.selectDocInitiated, name='select_doc_initiated'),
    # path('collab/view-initiated/<str:id1>/collab-docs/deselect/<str:id2>', views.deselectDocInitiated, name='deselect_doc_initiated'),
    # path('collab/view-initiated/<str:id1>/collab-docs/update/<str:id2>', views.updateDocInitiated, name='update_doc_initiated'),
    #
    # path('collab/view-initiated/<str:id1>/tasks/edit/<str:id2>', views.editTaskInitiated, name='edit_task_initiated'),
    # path('collab/view-accepted/<str:id1>/tasks/update/<str:id2>', views.updateTaskAccepted, name='update_task_accepted'),
    # path('collab/view-initiated/<str:id1>/tasks/delete/<str:id2>', views.deleteTaskInitiated, name='delete_task_initiated'),
    #
    # path('collab/view-initiated/<str:id1>/tasks/pin/<str:id2>', views.pinTask, name='pin_task'),
    # path('collab/view-accepted/<str:id1>/tasks/pin/<str:id2>', views.pinTask, name='pin_task'),
    #
    # path('collab/view-initiated/<str:id1>/collab-docs/delete-all', views.deleteAllDocsInitiated, name='delete_all_docs_initiated'),
    # path('collab/view-initiated/<str:id1>/upload-doc', views.uploadDoc, name='upload_doc'),
    # path('collab/view-accepted/<str:id1>/upload-doc', views.uploadDoc, name='upload_doc'),
    # path('collab/view-initiated/<str:id1>/add-task', views.addTask, name='task'),
    # path('collab/view-accepted/<str:id1>/add-task', views.addTask, name='task'),
    #
    # path('collab/view-initiated/<str:id>/removed/<str:username>', views.removeCollab, name='remove_collab'),
    # path('collab/view-initiated/<str:id>/reported/<str:username>', views.reportCollaborator, name='report_collaborator'),
    #
    # path('collab/view-accepted/<str:id>/remove-requested/<str:username>', views.requestRemoveCollab, name='request_remove_collab'),
    # path('collab/view-accepted/<str:id>/', views.showCollabAccepted, name='show_collab_accepted'),
    # path('collab/view-accepted/<str:id1>/collab-docs', views.showCollabDocsAccepted, name='collab_docs_accepted'),
    #
    # path('collab/view-accepted/<str:id1>/collab-docs/select/<str:id2>', views.selectDocAccepted, name='select_doc_accepted'),
    # path('collab/view-accepted/<str:id1>/collab-docs/deselect/<str:id2>', views.deselectDocAccepted, name='deselect_doc_accepted'),
    #
    # path('collab/view-accepted/<str:id1>/collab-docs/delete-all', views.deleteAllDocsAccepted, name='delete_all_docs_accepted'),
    #
    # path('collab/view-accepted/<str:id>/reported', views.reportResearcher, name='report_researcher'),
    # path('collab/view-accepted/<str:id>/left/<str:username>', views.leaveCollab, name='leave_collab'),
    # path('collab/view-initiated/<str:id>/leave-accepted/<str:username>', views.acceptLeaveCollab, name='accept_leave_collab'),
    # path('collab/view/<str:id>/offered/<str:username>', views.offerCollab, name='offer_collab'),
    # path('collab/view/<str:id>/declined/<str:username>', views.declineCollab, name='decline_collab'),

]

researchnote/models.py
from datetime import datetime
from django.db import models
from account.models import Researcher, Collab

class Note(models.Model):
    user = models.ForeignKey(Researcher, on_delete=models.CASCADE, related_name="research_note")
    collab = models.ForeignKey(Collab, null=True, blank=True, on_delete=models.SET_NULL, related_name="collab_research_note")
    title = models.CharField(max_length=200, verbose_name="")
    aims = models.CharField(max_length=255, verbose_name="")
    date_conducted = models.DateTimeField(null=True, blank=True, verbose_name="")
    location = models.CharField(max_length=200, null=True, blank=True, verbose_name="")
    setup = models.CharField(max_length=255,  null=True, blank=True, verbose_name="")
    method = models.TextField(null=True, blank=True, verbose_name="")
    result = models.TextField(null=True, blank=True, verbose_name="")
    observations = models.TextField(null=True, blank=True, verbose_name="")
    document = models.FileField(upload_to='research_notes/', null=True, blank=True, verbose_name="Attachment")
    is_pinned = models.BooleanField(max_length=5, null=True, blank=True, default = False)
    serial = models.CharField(max_length=4, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('serial',)

    def __str__(self):
        try:
            return str(self.title)
        except:
            return str(self.id)

researchnote/forms.py
from django import forms
from .models import Note
from django.db.models import Q
# from django.core.exceptions import ValidationError
# import datetime
from django.forms.widgets import NumberInput, DateInput
# from django.forms.widgets import TextInput

class NoteEditForm(forms.ModelForm):
    date_conducted = forms.DateTimeField(widget=DateInput(attrs={"type": "datetime-local",}, format="%Y-%m-%dT%H:%M",))
    class Meta:
        model = Note
        fields = ['title', 'aims', 'date_conducted', 'location', 'setup', 'method', 'result', 'observations', 'document']

class NoteForm(forms.ModelForm):
    title = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'Title'}))
    aims = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'Aims and Objective'}))
    location = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'Location Name'}))
    setup = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'Experimental Setup'}))
    method = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'Method/Procedure'}))
    result = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'Results'}))
    observations = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'Key Observations'}))

    date_conducted = forms.DateTimeField(widget=DateInput(attrs={"type": "datetime-local",}, format="%Y-%m-%dT%H:%M",))
    class Meta:
        model = Note
        fields = ['title', 'aims', 'date_conducted', 'location', 'setup', 'method', 'result', 'observations', 'document']

researchnote/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import NoteEditForm, NoteForm
from account.models import Collab
from .models import Note
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from .filters import NoteFilter
from django.core.paginator import Paginator

@login_required
def showNotesInitiated(request, id1):
    collab = Collab.objects.get(id=id1)
    if collab.researcher == request.user:
        context = {}
        filtered_notes = NoteFilter(
            request.GET,
            queryset = Note.objects.filter(collab__id=id1)
        )
        context['filtered_notes'] = filtered_notes
        paginated_filtered_notes = Paginator(filtered_notes.qs, 99)
        page_number = request.GET.get('page')
        notes_page_obj = paginated_filtered_notes.get_page(page_number)
        context['notes_page_obj'] = notes_page_obj
        total_notes = filtered_notes.qs.count()
        context['total_notes'] = total_notes
        context['collab'] = collab

        form = NoteForm()
        if request.method == 'POST':
            form = NoteForm(request.POST, request.FILES, None)
            if form.is_valid():
                form.save(commit=False).collab=collab
                form.save(commit=False).user=request.user
                form.save()
                reg = Note.objects.filter(collab=collab)[0]
                reg.serial = reg.id
                reg.save()

                messages.info(request, "The note has been added successfully")
                return redirect('notes_initiated', id1)
            else:
                messages.error(request, "Please review form input fields below")
        context['form'] = form

        return render(request, 'researchnote/notes.html', context)
    elif request.user in collab.collaborators.all():
        context = {}
        filtered_notes = NoteFilter(
            request.GET,
            queryset = Note.objects.filter(collab__id=id1)
        )
        context['filtered_notes'] = filtered_notes
        paginated_filtered_notes = Paginator(filtered_notes.qs, 99)
        page_number = request.GET.get('page')
        notes_page_obj = paginated_filtered_notes.get_page(page_number)
        context['notes_page_obj'] = notes_page_obj
        total_notes = filtered_notes.qs.count()
        context['total_notes'] = total_notes
        context['collab'] = collab

        form = NoteForm()
        if request.method == 'POST':
            form = NoteForm(request.POST, request.FILES, None)
            if form.is_valid():
                form.save(commit=False).collab=collab
                form.save(commit=False).user=request.user
                form.save()
                reg = Note.objects.filter(collab=collab)[0]
                reg.serial = reg.id
                reg.save()

                messages.info(request, "The note has been added successfully")
                return redirect('notes_accepted', id1)
            else:
                messages.error(request, "Please review form input fields below")
        context['form'] = form

        return render(request, 'researchnote/notes.html', context)
    else:
        return redirect('collab')

@login_required
def showNoteInitiated(request, id1, id2, **kwargs):
    collab = Collab.objects.get(id=id1)
    note = Note.objects.get(id=id2)
    if collab.researcher == request.user:

        form = NoteEditForm(instance=note)
        if request.method=='POST':
            form = NoteEditForm(request.POST, request.FILES, instance=note)
            if form.is_valid():
                form.save()
                messages.info(request, "The note has been updated successfully")

                return redirect('notes_initiated', id1)

        context = {'collab': collab, 'note':note, 'form':form}

        return render(request, 'researchnote/note_initiated.html', context)
    elif request.user in collab.collaborators.all():

        form = NoteEditForm(instance=note)
        if request.method=='POST':
            form = NoteEditForm(request.POST, request.FILES, instance=note)
            if form.is_valid():
                form.save()
                messages.info(request, "The note has been updated successfully")

                return redirect('notes_initiated', id1)

        context = {'collab': collab, 'note':note, 'form':form}

        return render(request, 'researchnote/note_initiated.html', context)
    else:
        return redirect('collab')

@login_required
def deleteNoteInitiated(request, id1, id2, **kwargs):
    collab = Collab.objects.get(id=id1)
    note = Note.objects.get(id=id2)
    if request.user == collab.researcher:
        obj = get_object_or_404(Note, id=id2)
        if request.method =="POST":
            obj.delete()
            messages.info(request, "The note has been deleted successfully")
            return redirect('notes_initiated', id1)
    elif request.user in collab.collaborators.all():
        obj = get_object_or_404(Note, id=id2)
        if request.method =="POST":
            obj.delete()
            messages.info(request, "The note has been deleted successfully")
            return redirect('notes_accepted', id1)
    else:
        return redirect('collab')
    return render(request, 'researchnote/note_confirm_delete.html', {'note':note, 'collab':collab})

@login_required
def pinNote(request, id1, id2, **kwargs):
    collab = Collab.objects.get(id=id1)
    if collab.researcher == request.user:
        note = Note.objects.get(id=id2)
        reg = Note.objects.filter(collab__id=id1)[0]
        serial_new = int(reg.serial) + 1
        serial_old = serial_new - 1
        reg.serial = serial_new
        note.serial = serial_old
        note.is_pinned = True
        reg.save()
        note.save()
        messages.info(request, "The note has been pinned successfully")
        return redirect('notes_initiated', id1)
    elif request.user in collab.collaborators.all():
        note = Note.objects.get(id=id2)
        reg = Note.objects.filter(collab__id=id1)[0]
        serial_new = int(reg.serial) + 1
        serial_old = serial_new - 1
        reg.serial = serial_new
        note.serial = serial_old
        note.is_pinned = True
        reg.save()
        note.save()
        messages.info(request, "The note has been pinned successfully")
        return redirect('notes_accepted', id1)
    else:
        return redirect('collab')

templates/researchnote/note_confirm_delete.html
{% extends 'board.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load humanize %}
{% load home_tags %}
{% block title %}
  <title>Delete Note</title>
  <meta name="description" content="">

{% endblock title %}

{% block content %}
{% include '_alerts.html' %}
<div class=" app-content">
	<div class="side-app">
  <br>
    <div class="container content-area">
      <div class="horizontal-content">
        <div class="row">
          <div class="d-flex justify-content-center">
            <div class="text-center card bg-info text-white form-group col-md-9">
              <br>
                {% if note.user == request.user %}
                <h4 > <span class="text-red">CAUTION!</span> Deleting {{note.title}} will affect all the information associated with it. Do you still wish to continue?</h4>
                <br>
                <form method="post">
                  {% csrf_token %}
                  {{ form|crispy }}
                  {% if collab.researcher == request.user %}
                  <input type="submit" class="btn btn-danger" value="Yes, delete"> <a class="btn btn-outline-light" href="{% url 'notes_initiated' collab.id %}">No, cancel</a>
                  {% elif request.user in collab.collaborators.all %}
                  <input type="submit" class="btn btn-danger" value="Yes, delete"> <a class="btn btn-outline-light" href="{% url 'notes_accepted' collab.id %}">No, cancel</a>
                  {% endif %}
                </form>

                {% else %}
                <h2 class="text-center">Access Denied!</h2>
                <br>
                {% endif %}
                <br>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content%}

templates/researchnote/note_initiated.html
{% extends 'board.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load humanize %}
{% load home_tags %}
{% block title %}
  <title>Note Details</title>
  <meta name="description" content="">

{% endblock title %}

{% block content %}

<div class=" app-content">
					<div class="side-app">
            <div class="row bg-light">
              <div class="col-md-3 ml-2">
                <br>
                <ul>
                  {% if request.user == collab.researcher %}
                  <li><a title="CollabDocs" href="{% url 'folders_initiated' collab.id %}"><i class="fas fa-folder-open text-info fa-2x mr-2"></i></a></li>
                  {% elif request.user in collab.collaborators.all %}
                  <li><a title="CollabDocs" href="{% url 'folders_accepted' collab.id %}"><i class="fas fa-folder-open text-info fa-2x mr-2"></i></a></li>
                  {% endif %}
                  {% if request.user == collab.researcher %}
                  <li><a title="Tasks" href="{% url 'tasks_initiated' collab.id %}"><i class="fas fa-tasks text-info fa-2x mr-2"></i></a></li>
                  {% elif request.user in collab.collaborators.all %}
                  <li><a title="Tasks" href="{% url 'tasks_accepted' collab.id %}"><i class="fas fa-tasks text-info fa-2x mr-2"></i></a></li>
                  {% endif %}
                  {% if request.user == collab.researcher %}
                  <li><a title="Scheduler" href="{% url 'calendarapp:schedules-initiated' collab.id %}"><i class="fas fa-calendar-check text-info fa-2x mr-2"></i></a></li>
                  {% elif request.user in collab.collaborators.all %}
                  <li><a title="Scheduler" href="{% url 'calendarapp:schedules-accepted' collab.id %}"><i class="fas fa-calendar-check text-info fa-2x mr-2"></i></a></li>
                  {% endif %}
                  <li><a title="ChatRoom" href="{% url 'chat' collab.id %}"><i class="fas fa-users text-info fa-2x mr-2"></i></a></li>
                  {% if request.user == collab.researcher %}
                  <li><a title="ResearchNotes" href="{% url 'notes_initiated' collab.id %}"><i class="fas fa-clipboard text-light-blue fa-2x mr-2"></i></a></li>
                  {% elif request.user in collab.collaborators.all %}
                  <li><a title="ResearchNotes" href="{% url 'notes_accepted' collab.id %}"><i class="fas fa-clipboard text-light-blue fa-2x mr-2"></i></a></li>
                  {% endif %}
                </ul>
              </div>
              <div class="col-md-5">
                <br>
                <ul>
                  {% if request.user == collab.researcher %}
                  <a href="{% url 'show_collab_initiated' collab.id %}"><h4 class=" mb-1"><span class="text-info">{{collab.title}}</span></h4></a>
                  {% elif request.user in collab.collaborators.all %}
                  <a href="{% url 'show_collab_accepted' collab.id %}"><h4 class=" mb-1"><span class="text-info">{{collab.title}}</span></h4></a>
                  {% endif %}
                </ul>
              </div>
              <div class="col-md-3 text-right">
                <br>
                <ul>
                  {% if collab.researcher.photograph %}
                  <li><sup><a href="{% url 'show_user' collab.researcher.user_Id %}"><img href="" src="{{ collab.researcher.photographURL }}" alt="Photograph" class="profile-not"><strong>{{collab.researcher.first_name|slice:":1"}}</strong> <strong>{{collab.researcher.last_name|slice:":1"}}</strong></a></sup></li>
                  {% else %}
                  <li><a href="{% url 'show_user' collab.researcher.user_Id %}"><i class="fa fa-user-circle text-info fa-2x"></i><strong>{{collab.researcher.first_name|slice:":1"}}</strong> <strong>{{collab.researcher.last_name|slice:":1"}}</strong></a></li>
                  {% endif %}
                  {% for person in collab.collaborators.all %}
                    {% if person.photograph %}
                      <li><sup><a href="{% url 'show_user' person.user_Id %}"><img href="" src="{{ person.photographURL }}" alt="Photograph" class="profile-not"><strong>{{person.first_name|slice:":1"}}</strong> <strong>{{person.last_name|slice:":1"}}</strong></a></sup></li>
                    {% else %}
                      <li><a href="{% url 'show_user' person.user_Id %}"><i class="fa fa-user-circle text-info fa-2x"></i><sup><strong>{{person.first_name|slice:":1"}}</strong> <strong>{{person.last_name|slice:":1"}}</strong></sup></a></li>
                    {% endif %}
                  {% endfor %}

                </ul>
              </div>
            </div>

            <hr class="bg-info">
              {% include '_alerts.html' %}
              <div class="container content-area">
                <div class="horizontal-content">

                  <div class="row">
      							<div class="col-xl-5 col-lg-12 col-md-12">
      								<div class="card">
      									<div class="card-body">
      										<div class="mt-4 mb-4">
      											<h3 class="text-info">{{note.title}}</h3>
                            <div class="mt-4 product-spec">
        											<div class="pro_detail">
        												<ul class="list-unstyled mb-0">
        													<li class="row border-bottom-0">
        														<div class="col-sm-6 text-muted mb-2">Aims and Objective</div>
        														<div class="col-sm-6 mb-2">{{note.aims|linebreaks}}</div>
        													</li>
        													<li class="border-bottom-0 row">
        														<div class="col-sm-6 text-muted mb-2">Date Conducted</div>
        														<div class="col-sm-6 mb-2">{{note.date_conducted|linebreaks}}</div>
        													</li>
                                  <li class="border-bottom-0 row">
        														<div class="col-sm-6 text-muted mb-2">Location Name</div>
        														<div class="col-sm-6 mb-2">{{note.location|linebreaks}}</div>
        													</li>
        													<li class="border-bottom-0 row">
        														<div class="col-sm-6 text-muted mb-2">Experimental Setup</div>
        														<div class="col-sm-6 mb-2">{{note.setup|linebreaks}}</div>
        													</li>
        													<li class="border-bottom-0 row">
        														<div class="col-sm-6 text-muted mb-2">Method/Procedure</div>
        														<div class="col-sm-6 mb-2">{{note.method|linebreaks}}</div>
        													</li>
        													<li class="border-bottom-0 row">
        														<div class="col-sm-6 text-muted mb-2">Results</div>
        														<div class="col-sm-6 mb-2">{{note.result}}</div>
        													</li>
        													<li class="border-bottom-0 row">
        														<div class="col-sm-6 text-muted mb-2">Key Observations</div>
        														<div class="col-sm-6 mb-2">{{note.observations}}</div>
        													</li>

        												</ul>
        											</div>
        										</div>
      										</div>
      									</div>
      								</div>
                      {% if note.user == request.user %}

                      <div class="modal fade" id="add1" role="dialog">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title text-info" id="inquiryModalLabel"><i class="fas fa-edit"></i> Edit Note</h4>
                                    <button type="button" class="close" data-dismiss="modal">
                                        <span>&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                  <br>
                                  <form method="post" class="form-group col-lg-12 text-info" enctype="multipart/form-data">
                                  {% csrf_token %}
                                  <div class="form-row">
                                      <div class="form-group col-sm-12 mb-2">
                                          {{ form.title|as_crispy_field }}
                                      </div>
                                  </div>
                                  <div class="form-row">
                                      <div class="form-group col-sm-12 mb-2">
                                          {{ form.aims|as_crispy_field }}
                                      </div>
                                  </div>
                                  <div class="form-row">
                                      <div class="form-group col-sm-12 mb-2">
                                          {{ form.date_conducted|as_crispy_field }}
                                      </div>
                                  </div>
                                  <div class="form-row">
                                      <div class="form-group col-sm-12 mb-2">
                                          {{ form.location|as_crispy_field }}
                                      </div>
                                  </div>
                                  <div class="form-row">
                                      <div class="form-group col-sm-12 mb-2">
                                          {{ form.setup|as_crispy_field }}
                                      </div>
                                  </div>
                                  <div class="form-row">
                                      <div class="form-group col-sm-12 mb-2">
                                          {{ form.method|as_crispy_field }}
                                      </div>
                                  </div>
                                  <div class="form-row">
                                      <div class="form-group col-sm-12 mb-2">
                                          {{ form.result|as_crispy_field }}
                                      </div>
                                  </div>
                                  <div class="form-row">
                                      <div class="form-group col-sm-12 mb-2">
                                          {{ form.observations|as_crispy_field }}
                                      </div>
                                  </div>
                                  <div class="form-row">
                                      <div class="form-group col-sm-12 mb-2">
                                          {{ form.document|as_crispy_field }}
                                      </div>
                                  </div>
                                  <input type="submit" class="form-group col-md-12 btn btn-info" value="OK">
                                </form>
                                </div>
                            </div>
                        </div>
                      </div>
                      <button class="btn btn-sm btn-info" data-toggle="modal" data-target="#add1"><strong><i class="fas fa-edit fa-1x mr-1"></i>Edit</strong></button>
                      {% endif %}

                    </div>

                    <div class="col-xl-4 col-md-12">
                      Submitted on {{note.created}}
                      <br>
                      by {% if note.user.photograph %}
                      <li><sup><a href="{% url 'show_user' note.user.user_Id %}"><img href="" src="{{ note.user.photographURL }}" alt="Photograph" class="profile-col"></a></sup></li>
                      {% else %}
                      <li><a href="{% url 'show_user' note.user.user_Id %}"><i class="fa fa-user-circle text-info fa-5x"></i></a></li>
                      {% endif %}

                    </div>

      						</div>
      					</div>
              </div>

          </div>
        </div>
        <br>

{% endblock content%}